export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST" ;
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS" ;
export const GET_CONVERSATION_FAIL = "GET_CONVERSATION_FAIL" ;

export const NEW_CONVERSATION_REQUEST = "NEW_CONVERSATION_REQUEST";
export const NEW_CONVERSATION_SUCCESS = "NEW_CONVERSATION_SUCCESS"
export const NEW_CONVERSATION_FAIL = "NEW_CONVERSATION_FAIL"