export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST" ;
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS" ;
export const GET_MESSAGE_FAIL = "GET_MESSAGE_FAIL" ;

export const NEW_MESSAGE_REQUEST = "NEW_MESSAGE_REQUEST";
export const NEW_MESSAGE_SUCCESS = "NEW_MESSAGE_SUCCESS"
export const NEW_MESSAGE_FAIL = "NEW_CONVERSATION_FAIL"