export const  ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST'
export const  ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const  ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL'


export const GET_REVIEW_REQUEST = 'GET_REVIEW_REQUEST'
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS'
export const GET_REVIEW_FAIL = 'GET_REVIEW_FAIL'
