export const  ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST'
export const  ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const  ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL'


export const GET_REVIEW_REQUEST = 'GET_REVIEW_REQUEST'
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS'
export const GET_REVIEW_FAIL = 'GET_REVIEW_FAIL'

export const  ADD_RESPONSE_REQUEST = 'ADD_RESPONSE_REQUEST'
export const  ADD_RESPONSE_SUCCESS = 'ADD_RESPONSE_SUCCESS'
export const  ADD_RESPONSE_FAIL = 'ADD_RESPONSE_FAIL'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'